name: 'test'
description: 'test
inputs:
  go-version-input:  # version of Go to use for govulncheck
    description: 'Version of Go to use for govulncheck'
    required: false
    default: '>=1.19.0'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ inputs.go-version-input }}
